#  IQR - used to detect outliers.

# INTER QUARTILE RANGE= (Q3-Q1)  USED TO FIND OUTLIERS

# Q1=25%
# Q3=75%
# LB=Q1-1.5*IQR
# UB=Q3+1.5*IQR

# IQR > UB
# IQR < LB

In [6]:
import pandas as pd
import numpy as np



In [23]:
data=[10, 12, 13, 14, 15, 16, 17, 18, 19, 40]
print(data)

[10, 12, 13, 14, 15, 16, 17, 18, 19, 40]


In [24]:
 data = np.array([10, 12, 13, 14, 15, 16, 17, 18, 19, 40])
print(data)

[10 12 13 14 15 16 17 18 19 40]


In [26]:
Q1=np.percentile(data, 25)
Q1

np.float64(13.25)

In [27]:
Q3=np.percentile(data, 75)
Q3

np.float64(17.75)

In [28]:
IQR = Q3- Q1
IQR

np.float64(4.5)

In [30]:
 lower_bound = Q1- 1.5 * IQR
lower_bound

np.float64(6.5)

In [31]:
upper_bound = Q3 + 1.5 * IQR
upper_bound

np.float64(24.5)

In [32]:
outlier_mask = (data < lower_bound) | (data > upper_bound)
outlier_mask

array([False, False, False, False, False, False, False, False, False,
        True])

In [34]:
outliers = data[outlier_mask]
outliers

array([40])

In [35]:
data_no_outliers = data[~outlier_mask]
data_no_outliers

array([10, 12, 13, 14, 15, 16, 17, 18, 19])

# HOMEWORK

In [20]:
#[2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, -10, -5, 50, 55, 60]

#detect the outliers from the above data

In [8]:
data=np.array([2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, -10, -5, 50, 55, 60])
sorted(data)

[np.int64(-10),
 np.int64(-5),
 np.int64(2),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(28),
 np.int64(50),
 np.int64(55),
 np.int64(60)]

In [10]:
Q1 = np.percentile(data, 25)
Q1

np.float64(9.25)

In [11]:
Q3=np.percentile(data,75)
Q3

np.float64(23.75)

In [13]:
IQR=Q3-Q1
IQR

np.float64(14.5)

In [14]:
 lower_bound = Q1- 1.5 * IQR
 lower_bound

np.float64(-12.5)

In [15]:
upper_bound = Q3+ 1.5 * IQR
upper_bound

np.float64(45.5)

In [17]:
 outlier_mask = (data < lower_bound) | (data > upper_bound)
 outlier_mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True])

In [19]:
 outliers = data[outlier_mask]
 outliers

array([50, 55, 60])