# ARRAY

In [5]:
# 1D 
import numpy as np


In [6]:
array_id = np.array([1,2,3,4])
print("1D array:")
print(array_id)

1D array:
[1 2 3 4]


In [10]:
array_id = np.array([[[1,2,3,4,5,6]]])
print("1D array:")
print(array_id)
array_id.ndim    # used to find dimension of an array

1D array:
[[[1 2 3 4 5 6]]]


3

In [26]:
# 2 D
array_2d = np.array([[1,2,3],[4,5,6]])

print("\n2D array:")
print(array_2d)   
array_2d.ndim
array_3d.shape


2D array:
[[1 2 3]
 [4 5 6]]


(1, 3, 2)

In [16]:
# 3 D  ----collection of 2D

array_3d = np.array([[[1,2,3],[4,5,6],[8,9,1]]])

print("\n3D array:")
print(array_3d)   
array_3d.ndim
array_3d.shape


3D array:
[[[1 2 3]
  [4 5 6]
  [8 9 1]]]


3

In [44]:
# create a 3d array of a shape [4,3,2]

array_3d = np.array([[[1,2],[3,4],[5,6]],
                     [[1,2],[3,4],[5,6]],
                     [[1,2],[3,4],[5,6]],
                     [[1,2],[3,4],[5,6]]])

print("\n3D array:")
print(array_3d)   
array_3d.ndim
array_3d.shape


3D array:
[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]


(4, 3, 2)

In [42]:
# creating two numpy arrays
arr1 = np.array([[10,5,6]])
arr2 = np.array([[6,5,8]])

# Addition
add_result= arr1+arr2
print("addition:", add_result)

# Substraction
s_result= arr1-arr2
print("substraction:", s_result)

# Multiplication
m_result= arr1*arr2
print("multiplication:", m_result)

# division
d_result= arr1/arr2
print("division:", d_result)

addition: [[16 10 14]]
substraction: [[ 4  0 -2]]
multiplication: [[60 25 48]]
division: [[1.66666667 1.         0.75      ]]


# HOMEWORK

In [3]:
#   How do you create a one-dimensional array in Python using NumPy with 5 elements, all set to zero?
import numpy as np
v = np.zeros(5)
print(v)

[0. 0. 0. 0. 0.]


In [5]:
#  Write a simple Python code to create a one-dimensional array with the numbers 1, 2, 3, 4, 5 using NumPy.

t= np.array([1,2,3,4,5])
print(t)

[1 2 3 4 5]


In [10]:
#  what is the code to create a 2x3 two-dimensional array in NumPy, filled with ones?

p=np.ones((2,3))
print(p)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#  Explain how to create a 2x2x2 three-dimensional array in NumPy with all elements set to 10.

s=np.full((2,2,2),10)          # np.full is used for constant value
print(s)

[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]


In [13]:
#  How can you add 2 to every element in a one-dimensional NumPy array with values [1, 2, 3, 4]? Show the code.
import numpy as np

t=np.array([1,2,3,4])
k=t+2                 # variable + no.
print(k)

[3 4 5 6]


In [14]:
#   Write a Python code to multiply each element in a one-dimensional NumPy array [2, 4, 6] by 3.
import numpy as np

c=np.array([4,6,8,2])
k=c*3
print(k)

[12 18 24  6]


In [20]:
#  How do you create a 2x2 two-dimensional array and add it to another 2x2 array with the same values in NumPy? Provide an example.

c=np.array([[1,2],
            [3,4]])
t=np.array([[1,2],
            [3,4]])
p=c+t
print(p)

[[2 4]
 [6 8]]


In [24]:
#  Show how to reshape a one-dimensional NumPy array with 6 elements [1, 2, 3, 4, 5, 6] into a 2x3 two-dimensional array.

v=np.array([1, 2, 3, 4, 5, 6])


reshaped_v=v.reshape(2, 3)
print(reshaped_v)

[[1 2 3]
 [4 5 6]]


In [9]:
# ssorting of 2d row wise
arr2d=np.array([[3,2,1],[1,1,4],[3,9,8]])
sorted_arr2d=np.sort(arr2d,axis=1)
print(arr2d)
print(sorted_arr2d)

[[3 2 1]
 [1 1 4]
 [3 9 8]]
[[1 2 3]
 [1 1 4]
 [3 8 9]]
