# ARRAY

In [5]:
# 1D 
import numpy as np


In [6]:
array_id = np.array([1,2,3,4])
print("1D array:")
print(array_id)

1D array:
[1 2 3 4]


In [10]:
array_id = np.array([[[1,2,3,4,5,6]]])
print("1D array:")
print(array_id)
array_id.ndim    # used to find dimension of an array

1D array:
[[[1 2 3 4 5 6]]]


3

In [26]:
# 2 D
array_2d = np.array([[1,2,3],[4,5,6]])

print("\n2D array:")
print(array_2d)   
array_2d.ndim
array_3d.shape


2D array:
[[1 2 3]
 [4 5 6]]


(1, 3, 2)

In [16]:
# 3 D  ----collection of 2D

array_3d = np.array([[[1,2,3],[4,5,6],[8,9,1]]])

print("\n3D array:")
print(array_3d)   
array_3d.ndim
array_3d.shape


3D array:
[[[1 2 3]
  [4 5 6]
  [8 9 1]]]


3

In [44]:
# create a 3d array of a shape [4,3,2]

array_3d = np.array([[[1,2],[3,4],[5,6]],
                     [[1,2],[3,4],[5,6]],
                     [[1,2],[3,4],[5,6]],
                     [[1,2],[3,4],[5,6]]])

print("\n3D array:")
print(array_3d)   
array_3d.ndim
array_3d.shape


3D array:
[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]


(4, 3, 2)

In [42]:
# creating two numpy arrays
arr1 = np.array([[10,5,6]])
arr2 = np.array([[6,5,8]])

# Addition
add_result= arr1+arr2
print("addition:", add_result)

# Substraction
s_result= arr1-arr2
print("substraction:", s_result)

# Multiplication
m_result= arr1*arr2
print("multiplication:", m_result)

# division
d_result= arr1/arr2
print("division:", d_result)

addition: [[16 10 14]]
substraction: [[ 4  0 -2]]
multiplication: [[60 25 48]]
division: [[1.66666667 1.         0.75      ]]


# HOMEWORK

In [3]:
#  1- How do you create a one-dimensional array in Python using NumPy with 5 elements, all set to zero?
import numpy as np
v = np.zeros(5)
print(v)

[0. 0. 0. 0. 0.]


In [5]:
# 2- Write a simple Python code to create a one-dimensional array with the numbers 1, 2, 3, 4, 5 using NumPy.

t= np.array([1,2,3,4,5])
print(t)

[1 2 3 4 5]


In [10]:
# 3- what is the code to create a 2x3 two-dimensional array in NumPy, filled with ones?

p=np.ones((2,3))
print(p)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# 4- Explain how to create a 2x2x2 three-dimensional array in NumPy with all elements set to 10.

s=np.full((2,2,2),10)          # np.full is used for constant value
print(s)

[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]


In [13]:
# 5- How can you add 2 to every element in a one-dimensional NumPy array with values [1, 2, 3, 4]? Show the code.
import numpy as np

t=np.array([1,2,3,4])
k=t+2                 # variable + no.
print(k)

[3 4 5 6]


In [14]:
#  6-  Write a Python code to multiply each element in a one-dimensional NumPy array [2, 4, 6] by 3.
import numpy as np

c=np.array([4,6,8,2])
k=c*3
print(k)

[12 18 24  6]


In [20]:
# 7- How do you create a 2x2 two-dimensional array and add it to another 2x2 array with the same values in NumPy? Provide an example.

c=np.array([[1,2],
            [3,4]])
t=np.array([[1,2],
            [3,4]])
p=c+t
print(p)

[[2 4]
 [6 8]]


In [24]:
# 8- Show how to reshape a one-dimensional NumPy array with 6 elements [1, 2, 3, 4, 5, 6] into a 2x3 two-dimensional array.

v=np.array([1, 2, 3, 4, 5, 6])


reshaped_v=v.reshape(2, 3)
print(reshaped_v)

[[1 2 3]
 [4 5 6]]


In [12]:
# sorting of 2d row wise
arr2d=np.array([[3,2,1],[1,1,4],[3,9,8]])
sorted_arr2d=np.sort(arr2d,axis=1)
print(arr2d)
print(sorted_arr2d)

[[3 2 1]
 [1 1 4]
 [3 9 8]]
[[1 2 3]
 [1 1 4]
 [3 8 9]]


In [4]:
#  1- How do you create a 1D NumPy array with the values [5, 2, 8, 1, 9] and sort it in ascending order
import numpy as np
p=np.array([5,2,8,1,9])
sorted_p=np.sort(p)       # this function is used to sort array in asec.
print(sorted_p)

[1 2 5 8 9]


In [6]:
#  2- Write code to sort a 1D NumPy array containing the values [10, 3, 7, 4, 6] in descending order


import numpy as np
p=np.array([5,2,8,1,9])
sorted_p=np.sort(p)[::-1]     # this function is used to sort array in descending order.
print(sorted_p)

[9 8 5 2 1]


In [3]:
#  3- Given a 2D NumPy array [[4, 1, 3], [9, 5, 2]], how do you sort each row in ascending order
import numpy as np
c=np.array([[5,8,54,2],
            [1,1,4,3],
            [8,6,2,4]])
sorted_c=np.sort(c)
print (sorted_c)

[[ 2  5  8 54]
 [ 1  1  3  4]
 [ 2  4  6  8]]


In [16]:
#  4- How can you sort a 2D NumPy array [[7, 2, 6], [1, 8, 3]] along the columns (axis=0)
t=np.array([[7,2,6],
           [1,8,3]])
sorted_t=np.sort(t,axis=0)          
print(sorted_t)

[[1 2 3]
 [7 8 6]]


In [17]:
# 5- Create a 1D NumPy array with values [1, 2, 3, 4, 5] and delete the element at indexweek3. How would you do this using NumPy
r=np.array([1,2,3,4,5])
np.delete(r,3)          # this function is used to delete value in the array
print(r)

[1 2 3 4 5]


In [25]:
#  6- Given a 2D NumPy array [[1, 2, 3], [4, 5, 6]], how do you delete the first row
y=np.array([[1,2,3],[4,5,6]])
k=np.delete(y,0,axis=0)
print(k)

[[4 5 6]]


In [27]:
#  7 - How do you delete the second column from a 2D NumPy array [[10, 20, 30], [40, 50, 60]]
o=np.array([[10,20,30],[40,50,60]])
h=np.delete(o,1,axis=1)
print(h)

[[10 30]
 [40 60]]


In [28]:
# 8 - Write code to add two 1D NumPy arrays [1, 2, 3] and [4, 5, 6] element-wise.
import numpy as np

f=np.array([50,20,30])
j=np.array([50,80,40])
t=f+j
print(t)

[100 100  70]


In [29]:
# 9- How do you perform element-wise addition of two 2D NumPy arrays [[1, 2], [3, 4]] and [[5, 6], [7, 8]]
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
h=a+b
print(h)

[[ 6  8]
 [10 12]]


In [6]:
# indexing of numpy
arr = np.array([10,20,30,40,50])
print([0])
print([2])
print([-1])

[0]
[2]
[-1]


In [7]:
arr2d=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr2d[:2,2:4])    # output [[7 8]
                        #         [11 12]

[[3 4]
 [7 8]]


In [9]:
import numpy as np
arr2d=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr2d[2,:])

[ 9 10 11 12]


In [2]:





import numpy as np
arr3d=np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])
print(arr3d)
print(arr3d[0,1,1:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[5 6]


In [6]:
import numpy as np
var=np.matrix([[1,2],[1,2]])
var1=np.matrix([[1,2],[1,2]])
print(var)
print()
print(var1)
print(var*var1)
print(var.dot(var1))

[[1 2]
 [1 2]]

[[1 2]
 [1 2]]
[[3 6]
 [3 6]]
[[3 6]
 [3 6]]


In [11]:
import numpy as np
p=np.matrix([[1,2,3],[4,5,6]])
print(p)
print()
print(np.transpose(p))
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]
[[1 1]
 [2 2]]
